# Generated by Django 4.0.1 on 2022-02-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], max_length=30)),
                ('id_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mentors', models.ManyToManyField(related_name='projects', through='mentors.Mentorship', to='mentors.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='mentorship',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.project'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('id_mentor', 'id_project')},
        ),
    ]
