version: '3.6'

services:
  # This service will launch a postgress DB. The serive name <db> is expected by django default db name.
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      # DB credentials to create the db
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  setup:
    restart: always
    build:
      context: .
      target: setup
    depends_on:
      db:
        condition: service_healthy
    
    environment:
      # DB credentials needed to create the superuser
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Django ENV variables to create the superuser
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}

      DJANGO_APP: ${DJANGO_APP}
      SEED_SIZE: ${SEED_SIZE}

    ports:
      - "8000:8000"
      # debugging port:
      - "3000:3000"



